In [49]:
import pandas as pd

In [50]:
relatorio = pd.read_html(r'https://www.gov.br/infraestrutura/pt-br/assuntos/transporte_aquaviario/sistema-portuario', header = 1) [0] 
df_relatorio = pd.DataFrame(relatorio)
display(relatorio)

,Nome,Estado,Nome.1,Estado.1,Nome.2,Estado.2,Unnamed: 6
0,1 - Cruzeiro do Sul,AC,14 - Monte Alegre,PA,27 - Jaguarão,RS,NaN
1,2 - Porto Acre,AC,15 - Óbidos,PA,28 - Santa Vitória do Palmar,RS,NaN
2,3 - Porto Walter,AC,16 - Oriximiná,PA,29 - Anhembi,SP,NaN
3,4 - Ibotirama,BA,17 - Porto de Moz,PA,30 - Jaú,SP,NaN
4,5 - Corumbá,MS,18 - Prainha,PA,31 - Panorama,SP,NaN
5,6 - Ladário,MS,19 - Senador José Porfírio,PA,32 - Pederneiras,SP,NaN
6,7 - Mundo Novo,MS,20 - Vitória de Xingu,PA,33 - Terminal Floresta,SP,NaN
7,8 - Cáceres,MT,21 - Santa Terezinha,PR,34 - Terminal São Miguel,SP,NaN
8,9 - Almeirim,PA,22 - Terra Roxa,PR,35 - Terminal Fazenda São joaquim,SP,NaN
9,10 - Altamira,PA,23 - Porto velho,RO,36 - Eclusa Tiête Montante,SP,NaN
10,11 - Gurupá,PA,24 - Estrela,RS,37 - Usina Diamante,SP,NaN
11,12 - Itaituba,PA,25 - Cachoeira do Sul,RS,38 - Usina Pioneiros,SP,NaN
12,13 - Juruti,PA,26 - Charqueadas,RS,39 - São Pedro,SP,NaN

In [51]:
df_relatorio = df_relatorio.drop('Unnamed: 6', axis = 1)
display(df_relatorio)

,Nome,Estado,Nome.1,Estado.1,Nome.2,Estado.2
0,1 - Cruzeiro do Sul,AC,14 - Monte Alegre,PA,27 - Jaguarão,RS
1,2 - Porto Acre,AC,15 - Óbidos,PA,28 - Santa Vitória do Palmar,RS
2,3 - Porto Walter,AC,16 - Oriximiná,PA,29 - Anhembi,SP
3,4 - Ibotirama,BA,17 - Porto de Moz,PA,30 - Jaú,SP
4,5 - Corumbá,MS,18 - Prainha,PA,31 - Panorama,SP
5,6 - Ladário,MS,19 - Senador José Porfírio,PA,32 - Pederneiras,SP
6,7 - Mundo Novo,MS,20 - Vitória de Xingu,PA,33 - Terminal Floresta,SP
7,8 - Cáceres,MT,21 - Santa Terezinha,PR,34 - Terminal São Miguel,SP
8,9 - Almeirim,PA,22 - Terra Roxa,PR,35 - Terminal Fazenda São joaquim,SP
9,10 - Altamira,PA,23 - Porto velho,RO,36 - Eclusa Tiête Montante,SP
10,11 - Gurupá,PA,24 - Estrela,RS,37 - Usina Diamante,SP
11,12 - Itaituba,PA,25 - Cachoeira do Sul,RS,38 - Usina Pioneiros,SP
12,13 - Juruti,PA,26 - Charqueadas,RS,39 - São Pedro,SP

In [52]:
colunas_nome = df_relatorio['Nome'].tolist() + df_relatorio['Nome.1'].tolist() + df_relatorio['Nome.2'].tolist()
colunas_estado = df_relatorio['Estado'].tolist() + df_relatorio['Estado.1'].tolist() + df_relatorio['Estado.2'].tolist()

df_relatorio = pd.DataFrame({'Nome': colunas_nome, 'Estado': colunas_estado})

display(df_relatorio)

                                 Nome Estado
0                 1 - Cruzeiro do Sul     AC
1                      2 - Porto Acre     AC
2                    3 - Porto Walter     AC
3                       4 - Ibotirama     BA
4                         5 - Corumbá     MS
5                         6 - Ladário     MS
6                      7 - Mundo Novo     MS
7                         8 - Cáceres     MT
8                        9 - Almeirim     PA
9                       10 - Altamira     PA
10                        11 - Gurupá     PA
11                      12 - Itaituba     PA
12                        13 - Juruti     PA
13                  14 - Monte Alegre     PA
14                        15 - Óbidos     PA
15                     16 - Oriximiná     PA
16                  17 - Porto de Moz     PA
17                       18 - Prainha     PA
18         19 - Senador José Porfírio     PA
19              20 - Vitória de Xingu     PA
20               21 - Santa Terezinha     PR
21                    22 - Terra Roxa     PR
22                   23 - Porto velho     RO
23                       24 - Estrela     RS
24              25 - Cachoeira do Sul     RS
25                   26 - Charqueadas     RS
26                      27 - Jaguarão     RS
27       28 - Santa Vitória do Palmar     RS
28                       29 - Anhembi     SP
29                           30 - Jaú     SP
30                      31 - Panorama     SP
31                   32 - Pederneiras     SP
32             33 - Terminal Floresta     SP
33           34 - Terminal São Miguel     SP
34  35 - Terminal Fazenda São joaquim     SP
35         36 - Eclusa Tiête Montante     SP
36                37 - Usina Diamante     SP
37               38 - Usina Pioneiros     SP
38                     39 - São Pedro     SP

In [53]:
df_relatorio['Nome'] = df_relatorio['Nome'].str.replace(r'^\d+\s+', '', regex=True)
df_relatorio['Nome'] = df_relatorio['Nome'].str.strip('-')

# Exibir o DataFrame atualizado
display(df_relatorio)

                             Nome Estado
0                 Cruzeiro do Sul     AC
1                      Porto Acre     AC
2                    Porto Walter     AC
3                       Ibotirama     BA
4                         Corumbá     MS
5                         Ladário     MS
6                      Mundo Novo     MS
7                         Cáceres     MT
8                        Almeirim     PA
9                        Altamira     PA
10                         Gurupá     PA
11                       Itaituba     PA
12                         Juruti     PA
13                   Monte Alegre     PA
14                         Óbidos     PA
15                      Oriximiná     PA
16                   Porto de Moz     PA
17                        Prainha     PA
18          Senador José Porfírio     PA
19               Vitória de Xingu     PA
20                Santa Terezinha     PR
21                     Terra Roxa     PR
22                    Porto velho     RO
23                        Estrela     RS
24               Cachoeira do Sul     RS
25                    Charqueadas     RS
26                       Jaguarão     RS
27        Santa Vitória do Palmar     RS
28                        Anhembi     SP
29                            Jaú     SP
30                       Panorama     SP
31                    Pederneiras     SP
32              Terminal Floresta     SP
33            Terminal São Miguel     SP
34   Terminal Fazenda São joaquim     SP
35          Eclusa Tiête Montante     SP
36                 Usina Diamante     SP
37                Usina Pioneiros     SP
38                      São Pedro     SP

In [54]:
titulo = "Relatório Portos Fluviais"
df_relatorio = df_relatorio.style.set_caption(titulo)

display(df_relatorio)

In [55]:
diretorio = r'C:\Users\ariva\Documents\projetosVsCode\pbl\\'
nome_arquivo = 'relatorioPortosFluviais.txt'
caminho_completo = diretorio + nome_arquivo

df_relatorio_string = df_relatorio.to_string()
with open(caminho_completo, 'w') as arquivo:
    arquivo.write(df_relatorio_string)
    
df_relatorio.to_
    
print(f"DataFrame exportado para {caminho_completo} com sucesso!")

AttributeError: 'Styler' object has no attribute 'to_csv'